### PR TITLE
Some small ESLint configuration improvements

### PR DESCRIPTION
**Pull request by lencioni**
- Sort alphabetically
- Disable deprecated and noisy `global-strict` rule
- Update ESLint to latest version

### CODE REVIEW

**Comment by wincent** [comment]
Thanks for the PR @lencioni! I'll add some comments inline, but as a heads up, the `next` branch is pretty far ahead of `master` at this point, so this won't apply cleanly.

Normally I'd want to merge `next` more frequently so `master` doesn't get too far out of date, but I've done some biggish refactors and it's not stable right now. Specifically there is one bad bug with the wrong note getting edited in filtered view (which I'm about to fix), and also the current tip of `next` (https://github.com/wincent/corpus/commit/d9b16dac32b66e4979e5d17f9842a982efec3c78) is busted because `async`/`await` is busted with the latest babel-core update (I actually think the problem is probably in regenerator and not Babel itself, because the generated output looks the same). I haven't reverted it yet because I haven't finished isolating the cause (kind of painful with the way `node_modules` get nested and bisecting is hard), but if you wanted to try out `next` you'd just need to revert that commit.

**Comment by lencioni** [comment]
Thanks for the heads up on the `next` branch. I'll check it out next time I mess around with this project.

**Comment by lencioni** [comment]
Also, feel free to just close these PRs out--I just wanted to get my feet wet here and see if I could contribute anything useful. NBD either way.

**Comment by wincent** [comment]
Merged two of the commits, but not https://github.com/lencioni/corpus/commit/8a942480c18399083d320aa319d151943b7e4a39, as I think any errors you're getting are anomalies.

Thanks once again!

**Pull request closed without merging**
